# 1 Задание 
print("Hello, enter type your pet")
a=input()
print("Enter name your pet")
b=input()
print("Enter age your pet")
c=input()
print ("your pet is") 
print(a)
print("his name is")
print(b)
print("and he is ")
print(c)
print("years old")